### ISSUE TITLE
Basic Flow Clip Text Encode error

### ISSUE THREAD

**Issue by Piscabo** [shadowcz007/comfyui-hydit-lowvram#1]
Trying with the Basic Workflow, but run into error:
![image](https://github.com/user-attachments/assets/c4ef0006-213a-46c4-a1f4-f281fdda0c4a)

2024-07-22 17:21:21.715 - __init__.py:1706 - INFO - got prompt
[rgthree] Using rgthree's optimized recursive execution.
2024-07-22 17:21:21.966 - __init__.py:1706 - ERROR - !!! Exception during processing!!! 'tuple' object has no attribute 'pop'
2024-07-22 17:21:21.967 - __init__.py:1706 - ERROR - Traceback (most recent call last):
  File "H:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\nodes.py", line 59, in encode
    cond = output.pop("cond")
           ^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'pop'

**Comment by handles98** [comment]
same
